#!/usr/bin/env bash

if [[ "$1" == "run-server" ]]; then
  echo running a dev server...
  yarn http-server .
elif [[ "$1" == "watch-scss" ]]; then
  echo running live build of scss...
  yarn node-sass --watch style.scss --output .
else
  echo choose a command: run-server or watch-scss
fi
